backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
media_folder: src/images
public_folder: /images

collections:
  - name: "site" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Site" # Used in the UI, ie.: "New Post"
    slug: "{{title}}"
    folder: "src"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "home" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Home" # Used in the UI, ie.: "New Post"
    slug: "{{title}}"
    file: "src/index.md"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
        - {label: "Body", name: "body", widget: "markdown"}
