backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
media_folder: src/images
public_folder: /images

collections:
  - name: "site" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Site Pages" # Used in the UI, ie.: "New Post"
    files:
      - label: "Home"
        name: "home"
        file: "src/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "About Us"
        name: "about-us"
        file: "src/about-us.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact Us"
        name: "contact"
        file: "src/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Services"
        name: "services"
        file: "src/services.md"
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
        - {label: "Body", name: "body", widget: "markdown"}
