backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
media_folder: src/images
public_folder: /images

collections:
  - name: "site" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Site Pages" # Used in the UI, ie.: "New Post"
    files:
      - label: "Home"
        name: "home"
        file: "src/index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner", name: "banner", widget: "image", required: false}
          - {label: "Header Text", name: "header_tag", widget: "string"}
          - {label: "Top Callout", name: "top_callout", widget: "markdown"}
          - {label: "Specialty 1", name: "specialty1_text", widget: "markdown"}
          - {label: "Specialty 2", name: "specialty2_text", widget: "markdown"}
          - {label: "Specialty 3", name: "specialty3_text", widget: "markdown"}
          - {label: "Specialty 4", name: "specialty4_text", widget: "markdown"}
          - {label: "Schedule Form", name: "schedule_form", widget: "string"}
          - {label: "Green Text", name: "green_text", widget: "markdown"}
          - {label: "Green Callout 1", name: "green_callout1", widget: "markdown"}
          - {label: "Green Callout 2", name: "green_callout2", widget: "markdown"}
          - {label: "Green Callout 3", name: "green_callout3", widget: "markdown"}
          - {label: "Just Saying Image", name: "saying_icon", widget: "image"}
          - {label: "Just Saying Text", name: "saying_text", widget: "markdown"}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "About Us"
        name: "about-us"
        file: "src/about-us.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner", name: "banner", widget: "image", required: false}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact Us"
        name: "contact"
        file: "src/contact.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner", name: "banner", widget: "image", required: false}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Services"
        name: "services"
        file: "src/services.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner", name: "banner", widget: "image", required: false}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Dr. Green"
        name: "drgreen"
        file: "src/drjamesgreen.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner", name: "banner", widget: "image", required: false}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Dr. Bowen"
        name: "drbowen"
        file: "src/drdianebowen.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner", name: "banner", widget: "image", required: false}
          - {label: "Layout", name: "layout_type", widget: "hidden", default: "page"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "services" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Services" # Used in the UI, ie.: "New Post"
    folder: "src/services"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: ["Face", "Breast", "Body", "Medical Spa", "Health & Wellness"]}
      - {label: "Banner", name: "banner", widget: "image", required: false}
      - {label: "Layout", name: "layout_type", widget: "hidden", default: "service"}
      - {label: "Summary", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
